/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.aritmatika;

/**
 *
 * @author Nabila AAP
 */
public class Frame extends javax.swing.JFrame {
    String jns="" ;
    int jml;
    
    
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        jns = null;
        panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        htg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbox2 = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        thasil = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(153, 255, 51));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        panel.setLayout(null);

        htg.setBackground(new java.awt.Color(0, 0, 0));
        htg.setForeground(new java.awt.Color(51, 255, 0));
        htg.setText("HITUNG");
        htg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htgActionPerformed(evt);
            }
        });
        panel.add(htg);
        htg.setBounds(201, 210, 90, 23);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(20, 60, 90, 13);

        cbox2.setBackground(new java.awt.Color(204, 204, 204));
        cbox2.setForeground(new java.awt.Color(153, 255, 0));
        cbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox2ActionPerformed(evt);
            }
        });
        panel.add(cbox2);
        cbox2.setBounds(170, 60, 150, 20);

        bil1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(20, 90, 90, 13);

        b1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        panel.add(b1);
        b1.setBounds(170, 90, 150, 19);

        b2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        panel.add(b2);
        b2.setBounds(170, 120, 150, 19);

        b3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        panel.add(b3);
        b3.setBounds(170, 150, 150, 19);

        bil2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(20, 120, 90, 13);

        bil3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(20, 150, 90, 13);

        bil4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(20, 180, 90, 13);

        b4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        panel.add(b4);
        b4.setBounds(170, 180, 150, 19);

        thasil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panel.add(thasil);
        thasil.setBounds(130, 250, 210, 50);
        panel.add(ket);
        ket.setBounds(140, 20, 120, 20);

        getContentPane().add(panel);
        panel.setBounds(20, 90, 360, 310);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(120, 20, 180, 21);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 60, 90, 13);

        cbox.setBackground(new java.awt.Color(204, 204, 204));
        cbox.setForeground(new java.awt.Color(0, 255, 255));
        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--  Pilih Salah Satu --", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });
        jPanel2.add(cbox);
        cbox.setBounds(210, 60, 160, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 420);

        setSize(new java.awt.Dimension(416, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox2ActionPerformed
        // TODO add your handling code here:
        getJumlah();
        getKurang();
        getKali();
        getBagi();
 
    }//GEN-LAST:event_cbox2ActionPerformed

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_cboxActionPerformed

    private void htgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htgActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1,a2,a3,a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b2.getText().toString());
        a4 = Double.parseDouble(b2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2) {
                hsl = a1 + a2;
                thasil.setText(""+a1 + " + " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2) {
                hsl = a1 - a2;
                thasil.setText(""+a1 + " - " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2) {
                hsl = a1 * a2;
                thasil.setText(""+a1 + " x " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " x " + a2 + " x " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " x " + a2 + " x " + a3 + " x " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml == 2) {
                hsl = a1 / a2;
                thasil.setText(""+a1 + " / " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " / " + a2 + " / " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " / " + a2 + " / " + a3 + " / " + a4 + " = " + hsl);
            }
        }
    }//GEN-LAST:event_htgActionPerformed

    public void setJenis(){
        if(cbox.getSelectedItem().equals("Penjumlahan")){
        jns = "Penjumlahan";
        ket.setText("Penjumlahan");
        panel.setVisible(true);
        cbox2.setEnabled(true);
        }
        else if(cbox.getSelectedItem().equals("Pengurangan")){
        jns = "Pengurangan";
        ket.setText("Pengurangan");
        panel.setVisible(true);
        cbox2.setEnabled(true);
        }
        else if(cbox.getSelectedItem().equals("Perkalian")){
        jns = "Perkalian";
        ket.setText("Perkalian");
        panel.setVisible(true);
        cbox2.setEnabled(true);
        }
        else if(cbox.getSelectedItem().equals("Pembagian")){
        jns = "Pembagian";
        ket.setText("Pembagian");
        panel.setVisible(true);
        cbox2.setEnabled(true);
        }
        /* else{
            jns = null;
            panel.setVisible(false);
        } */
    }
    
    public void getJumlah(){
        if(cbox2.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        }
        else if(cbox2.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }
        else if(cbox2.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    }
    
    public void getKurang(){
        if(cbox2.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        }
        else if(cbox2.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }
        else if(cbox2.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    }
    
    public void getKali(){
        if(cbox2.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        }
        else if(cbox2.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }
        else if(cbox2.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    }
    
    public void getBagi(){
        if(cbox2.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        }
        else if(cbox2.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }
        else if(cbox2.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JComboBox<String> cbox2;
    private javax.swing.JButton htg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables
}
